version: '3.7'
services:
  web-app:
    image: robounord/uptime-kuma-rest:1.03
    container_name: web-app
    networks:
    - public
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.monitor-api.rule=Host(`monitor-api.unord.dk`)
      - traefik.http.routers.monitor-api.entrypoints=websecure
      - traefik.http.routers.monitor-api.tls=true
      - traefik.http.services.monitor-api.loadbalancer.server.port=8000
      - traefik.http.services.monitor-api.loadbalancer.server.scheme=http
      - traefik.http.services.monitor-api.loadbalancer.passHostHeader=true
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      PSQL_HOST: ${PSQL_HOST}
      PSQL_DATABASENAME: ${PSQL_DATABASENAME}
      PSQL_PORT: ${PSQL_PORT}
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
networks:
  public:
    external: true
