# Generated by Django 5.0.4 on 2024-04-26 07:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Monitor Group Name')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Monitor Name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('ops_url', models.URLField(blank=True, null=True, verbose_name='OPS URL')),
                ('monitor_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type of Monitor')),
                ('interval', models.IntegerField(verbose_name='Interval in seconds')),
                ('silenced', models.BooleanField(default=False, verbose_name='Silenced')),
                ('uptime_kuma_monitor_id', models.IntegerField(verbose_name='Uptime Kuma Monitor ID')),
                ('users_main_maintainers', models.ManyToManyField(blank=True, related_name='maintained_monitors', to=settings.AUTH_USER_MODEL, verbose_name='Main Maintainers')),
                ('users_main_supporters', models.ManyToManyField(blank=True, related_name='supported_monitors', to=settings.AUTH_USER_MODEL, verbose_name='Main Supporters')),
                ('monitor_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors', to='uptime_kuma_rest_app.monitorgroup', verbose_name='Monitor Group')),
            ],
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('forced_down', models.BooleanField(default=False, verbose_name='Forced Down')),
                ('assigned_users', models.ManyToManyField(related_name='heartbeats', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Users')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='uptime_kuma_rest_app.monitor', verbose_name='Monitor')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heartbeats', to='uptime_kuma_rest_app.status', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('heartbeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='uptime_kuma_rest_app.heartbeat', verbose_name='Heartbeat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
